config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # moduleで、URLを変更せず、ファイル構成だけ指定のパスにする。
  # URL /users/sign_in ...

  devise_scope :user do
    # ゲストログイン
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in',as: 'guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {

    # ユーザー新規登録画面
    registrations: "public/registrations",
    # ログイン画面
    sessions: 'public/sessions'

  }

  scope module: :public do
    # トップページ　初期表示
    root to: 'homes#top'
    # アバウトページ
    get 'about' => 'homes#about', as: 'about'

    # マイページ
    get 'users/my_page' => 'users#my_page', as: 'my_page'
    # プロフィール編集画面
    get 'users/information/edit'=> 'users#edit', as: 'edit_information_users'
    # プロフィール更新
    patch 'users/information' => 'users#update', as: 'update_information_users'
    # 退会確認画面
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 退会処理
    patch 'users/goodbye' => 'users#goodbye', as: 'goodbye'
    # ユーザー詳細画面
    resources :users, only: [:show] do

      # ユーザーの投稿内容一覧
      get 'posts'
      # ユーザーのコメント一覧
      get 'comments'
       # ユーザーのいいね一覧
      get 'favorites'
    end

    # 投稿内容一覧（ユーザー投稿全て）⇒　削除
    # get 'posts/user_index' => 'posts#user_index', as: 'user_index'
    resources :posts do

      # コメント機能
      resources :comments, only: [:create,:edit,:update,:destroy]
      # いいね機能
      resources :favorites, only: [:create, :destroy]
    end

    # ねこずかん（種類一覧）系
    resources :types, only: [:index, :show]

  end

    # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

    # 管理者ログイン
    sessions: "admin/sessions"
  }

  # 管理者用
  get 'admin' => 'admin/homes#top', as: 'admin_home_top'

  namespace :admin do

    # ユーザー一覧系
    resources :users, only: [:index, :show, :edit, :update]
    # 投稿内容一覧系
    resources :posts, only: [:show, :destroy]
    # コメント一覧系
    resources :comments, only: [:index, :destroy]
    # ねこずかん（種類一覧）系
    resources :types

  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  # comment と user の 1 : N のアソシエーション実装
  belongs_to :user
  # comment と post の 1 : N のアソシエーション実装
  belongs_to :post

  # バリデーション(入力必須のバリデーションをまとめる。)
  with_options presence: true do

    # コメント内容
    validates :comment_word

  end

  # コメント日時
  def get_comment_date

    # 日時フォーマットを修正
    created_at.strftime('%Y/%m/%d %H:%M')

  end

  # コメント省略
  def get_comment_word

    # 10文字以上の場合
    if comment_word.length > 10

      # 最初の10文字取得
      word = comment_word.slice(0..10)
      # コメントを省略して出力する。（最初の10文字 + "..."）
      word + "..."

    else

      comment_word

    end

  end

  # タイトル取得（第一引数：投稿ID）
  def get_post_title(post_id)

    # 投稿IDで検索して、0番目のタイトルを取得する。
    Post.where(id: post_id).pluck(:title)[0]

  end

  # 投稿者ID取得（第一引数：投稿ID）
  def get_post_user_id(post_id)

    # 投稿IDで検索して、0番目のユーザーIDを取得する。
    Post.where(id: post_id).pluck(:user_id)[0]

  end

  # 投稿ユーザーの取得（第一引数：投稿ID）
  def get_post_user_name(post_id)

    # 投稿モデルのユーザーIDを取得。
    post_user_id = get_post_user_id(post_id)
    # 取得したユーザーIDで、ユーザーネームを取得。
    User.where(id: post_user_id).pluck(:name)[0]

  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  # コントローラーに設定して、ログイン済管理者のみにアクセスを許可する
  before_action :authenticate_admin!

  # コメント一覧
  def index

    # コメントモデルから1ページ分（データ30件）取得（降順）
    @comments = Comment.page(params[:page]).per(30).order(id: "DESC")

  end

  # コメント削除機能
  def destroy

    # 1件コメント取得
    comments = comment_find_params_id
    # 削除
    comments.destroy
    # フラッシュメッセージ
    notice("コメントを削除しました。")
    # 処理後遷移先
    redirect_to admin_comments_path

  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class = "d-flex justify-content-between">
  <h4 class = "field m-3">コメント一覧</h4>
</div>
<div>
  <!-- テーブルヘッダー部分 -->
  <table class = "table" >
    <thead class = "table-primary">
      <tr>
        <th>ID</th>
        <th>投稿日時</th>
        <th>タイトル</th>
        <th>投稿ユーザー</th>
        <th>コメント内容</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <!-- コメントモデルから1ページ分（データ30件） -->
      <% @comments.each do |f| %>
      <tr>
        <!-- コメントID -->
        <td><%= f.id %></td>
        <!-- コメント日時 -->
        <td><%= f.get_comment_date %></td>
        <!-- タイトル -->
        <td>
          <!-- 投稿内容の情報へのリンク -->
          <%= link_to admin_post_path(f.post_id) do %>
            <%= f.get_post_title(f.post_id) %>
          <% end %>
        </td>
        <!-- 投稿ユーザー -->
        <td>
          <!-- 投稿ユーザーの情報へのリンク -->
          <%= link_to admin_user_path(f.user_id) do %>
            <%= f.get_post_user_name(f.post_id) %>
          <% end %>
        </td>
        <!-- コメント内容 -->
        <td><%= f.get_comment_word %></td>
        <!-- 削除ボタン -->
        <td><%= link_to "削除", admin_comment_path(f.id), method: :delete, class:"btn btn-danger", "data-confirm" => "OKボタンを押すと削除します。本当に削除しますか？"  %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- ページリンク -->
<div class = "d-flex justify-content-center">
  <%= paginate @comments %>
</div>