config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # moduleで、URLを変更せず、ファイル構成だけ指定のパスにする。
  # URL /users/sign_in ...

  devise_scope :user do
    # ゲストログイン
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in',as: 'guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {

    # ユーザー新規登録画面
    registrations: "public/registrations",
    # ログイン画面
    sessions: 'public/sessions'

  }

  scope module: :public do
    # トップページ　初期表示
    root to: 'homes#top'
    # アバウトページ
    get 'about' => 'homes#about', as: 'about'

    # マイページ
    get 'users/my_page' => 'users#my_page', as: 'my_page'
    # プロフィール編集画面
    get 'users/information/edit'=> 'users#edit', as: 'edit_information_users'
    # プロフィール更新
    patch 'users/information' => 'users#update', as: 'update_information_users'
    # 退会確認画面
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 退会処理
    patch 'users/goodbye' => 'users#goodbye', as: 'goodbye'
    # ユーザー詳細画面
    resources :users, only: [:show] do

      # ユーザーの投稿内容一覧
      get 'posts'
      # ユーザーのコメント一覧
      get 'comments'
       # ユーザーのいいね一覧
      get 'favorites'
    end

    # 投稿内容一覧（ユーザー投稿全て）⇒　削除
    # get 'posts/user_index' => 'posts#user_index', as: 'user_index'
    resources :posts do

      # コメント機能
      resources :comments, only: [:create,:edit,:update,:destroy]
      # いいね機能
      resources :favorites, only: [:create, :destroy]
    end

    # ねこずかん（種類一覧）系
    resources :types, only: [:index, :show]

  end

    # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

    # 管理者ログイン
    sessions: "admin/sessions"
  }

  # 管理者用
  get 'admin' => 'admin/homes#top', as: 'admin_home_top'

  namespace :admin do

    # ユーザー一覧系
    resources :users, only: [:index, :show, :edit, :update]
    # 投稿内容一覧系
    resources :posts, only: [:show, :destroy]
    # コメント一覧系
    resources :comments, only: [:index, :destroy]
    # ねこずかん（種類一覧）系
    resources :types

  end

end

app/controllers/admin/types_controller.rb
class Admin::TypesController < ApplicationController

  # コントローラーに設定して、ログイン済管理者のみにアクセスを許可する
  before_action :authenticate_admin!

  # ねこずかん（種類一覧）
  def index

    # 種類モデルから1ページ分（データ30件）取得（降順）
    @types = Type.page(params[:page]).per(30).order(id: "DESC")

  end

  # 種類登録画面
  def new

    # データを受け取り新規登録するためのインスタンス作成
    @type = Type.new

  end

  # 種類情報の新規登録処理
  def create

    # データを受け取り新規登録するためのインスタンス作成
    @type = Type.new(type_params)
    # 登録時チェック
    if @type.save

      # 成功時処理
      # フラッシュメッセージ
      notice("ねこずかんを追加しました。")
      # 処理後遷移先
      redirect_to admin_type_path(@type.id)

    else

      # 失敗時処理
      # 処理後遷移先
      render :new
    end

  end

  # 種類詳細画面
  def show

    # 1件種類情報取得
    @type = type_find_params_id

  end

  # 種類情報の更新処理
  def edit

    # 1件種類情報取得
    @type = type_find_params_id

  end

  # 種類情報の更新処理
  def update

    # 1件種類情報取得
    @type = type_find_params_id

    # 更新時チェック(nバリデーションチェック)
    if @type.update(type_params)

      # 成功時処理
      # フラッシュメッセージ
      notice("ねこずかんを更新しました。")
      # 処理後遷移先
      redirect_to admin_type_path(@type.id)

    else

      # 失敗時処理
      # 処理後遷移先
      render :edit

    end

  end

  # 種類情報の更新処理
  def destroy

    # 1件種類情報取得
    type = type_find_params_id
    # 削除
    type.destroy
    # フラッシュメッセージ
    notice("ねこずかんから１件削除しました。")
    # 処理後遷移先
    redirect_to admin_types_path

  end

  private

  # ストロングパラメータ(Web上から受けつけたパラメータが、本当に安全なデータかどうかを検証した上で、取得するための仕組み)
  def type_params

    # typeモデルのカラム
    params.require(:type).permit(:image,:name,:body_length,:country,:tag_list,:detail)

  end
end

app/helpers/admin/types_helper.rb
module Admin::TypesHelper
end

app/views/admin/types/edit.html.erb
<div class = "d-flex justify-content-between">
  <h4 class = "field m-3">種類変更</h4>
</div>
<div>
  <%= form_with model: @type, url: admin_type_path, method: :patch do |f| %>
  <!-- エラーメッセージ -->
  <%= render 'layouts/error_messages', model: f.object %>
    <div class = "field my-2 offset-1">
      <table class = "table table-borderless" >
        <tbody>
          <!-- 投稿画像 -->
          <tr>
            <th>投稿画像</th>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <!-- 種類名 -->
          <tr>
            <th>種 類 名</th>
            <td><%= f.text_field :name, :placeholder => "三毛猫", autofocus: true, class: 'form-control' %></td>
          </tr>
          <!-- 体長 -->
          <tr>
            <th>体　　長</th>
            <td><%= f.text_field :body_length, :placeholder => "26~28cm" , class: 'form-control' %></td>
          </tr>
          <!-- 原産国 -->
          <tr>
            <th>原 産 国</th>
            <td><%= f.text_field :country, :placeholder => "日本" , class: 'form-control' %></td>
          </tr>
          <!-- タグリスト -->
          <tr>
            <th>タグリスト</th>
            <td><%= f.text_field :tag_list, :placeholder => "ペット,三毛猫" , value: @type.tag_list.join(','), class: 'form-control' %></td>
          </tr>
          <!-- 詳細 -->
          <tr>
            <th>詳　　細</th>
            <td><%= f.text_area :detail, :placeholder => "特徴や性格などを入力。" , size: "50x10", class: 'form-control' %></td>
          </tr>
          <tr>
            <th></th>
            <td>
              <!-- 変更ボタン -->
              <%= f.submit '変更', class:"btn btn-success btn-block" %>
            </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>

app/views/admin/types/index.html.erb
<div class = "d-flex justify-content-between">
  <h4 class = "field m-3">ねこずかん</h4>
   <!-- 種類登録ボタン -->
   <%= link_to new_admin_type_path, class:"nav-link text-right" do %>
   <i class="fas fa-cat fa-lg"></i>
    <% end %>
</div>
<div>
  <!-- テーブルヘッダー部分 -->
  <table class = "table" >
    <thead class = "table-success">
      <tr>
        <th>ID</th>
        <th>投稿日時</th>
        <th>種類名</th>
        <th>タグ</th>
      </tr>
    </thead>
    <tbody>
      <!-- 種類モデルから1ページ分（データ30件） -->
      <% @types.each do |f| %>
      <tr>
        <!-- 種類ID -->
        <td><%= f.id %></td>
        <!-- 投稿日時 -->
        <td><%= f.get_posted_date %></td>
        <!-- 種類名 -->
        <td>
          <!-- 種類詳細画面へのリンク -->
          <%= link_to admin_type_path(f.id) do %>
            <%= f.name %>
          <% end %>
        </td>
        <!-- タグリスト（登録した分だけ出力する。） -->
        <td>
          <%= render 'layouts/admin_type_tag_list', tag_list: f.tag_list %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- ページリンク -->
<div class = "d-flex justify-content-center">
  <%= paginate @types %>
</div>

app/views/admin/types/new.html.erb
<div class = "d-flex justify-content-between">
  <h4 class = "field m-3">種類登録</h4>
</div>
<div>
  <!-- 入力フォーム -->
  <%= form_with model: @type, url: admin_types_path, method: :post do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class = "field my-2 offset-1">
      <table class = "table table-borderless" >
        <tbody>
          <!-- 投稿画像 -->
          <tr>
            <th>投稿画像</th>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <!-- 種類名 -->
          <tr>
            <th>種 類 名</th>
            <td><%= f.text_field :name, :placeholder => "三毛猫", autofocus: true, class: 'form-control' %></td>
          </tr>
          <!-- 体長 -->
          <tr>
            <th>体　　長</th>
            <td><%= f.text_field :body_length, :placeholder => "26~28cm" , class: 'form-control' %></td>
          </tr>
          <!-- 原産国 -->
          <tr>
            <th>原 産 国</th>
            <td><%= f.text_field :country, :placeholder => "日本" , class: 'form-control' %></td>
          </tr>
          <!-- タグリスト（半角カンマで区切って登録） -->
          <tr>
            <th>タグリスト</th>
            <td><%= f.text_field :tag_list, :placeholder => "ペット,三毛猫" , value: @type.tag_list.join(','), class: 'form-control' %></td>
          </tr>
          <!-- 詳細-->
          <tr>
            <th>詳　　細</th>
            <td><%= f.text_area :detail, :placeholder => "特徴や性格などを入力。" , size: "50x10", class: 'form-control' %></td>
          </tr>
          <tr>
            <th></th>
            <td>
              <!-- 登録 -->
              <%= f.submit '登録', class:"btn btn-success btn-block" %>
            </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>

app/views/admin/types/show.html.erb
<div class = "row">
  <div class = "col-md-6 field my-2 offset-1">
    <div class = "items_image offset-1">
      <!-- 種類名像 -->
      <h4><%= @type.name %></h4>
      <!-- 投稿画像 -->
      <%= image_tag @type.get_image(300) %>
    </div>
    <div class = "main my-3 offset-1">
      <!-- 体長 -->
      <div class="d-flex justify-content-between">
        <strong class>体　　　長</strong>
        <%= @type.body_length %>
      </div>
      <!-- 原産国 -->
      <div class="d-flex justify-content-between my-4">
        <strong class>原　産　国</strong>
        <%= @type.country %>
      </div>
      <!-- タグリスト（登録した分だけ出力する。） -->
      <div class="col-md d-flex justify-content-start">
        <table class = "table table-borderless">
          <td><%= render 'layouts/admin_type_tag_list', tag_list: @type.tag_list %></td>
        </table>
      </div>
      <!-- 詳細 -->
      <div class="d-flex justify-content-between my-4">
        <strong class>詳　　　細</strong>
      </div>
      <div class="col-md d-flex justify-content-between my-4">
        <%= @type.detail %>
      </div>
      <div class="d-flex justify-content-lg-between">
        <!-- 編集ボタン -->
        <%= link_to "編集", edit_admin_type_path(@type.id), class:"btn btn-success" %>
        <!-- 削除ボタン -->
        <%= link_to "削除", admin_type_path(@type.id), method: :delete, class:"btn btn-danger" %>
    </div>
    </div>
  </div>
</div>