config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # moduleで、URLを変更せず、ファイル構成だけ指定のパスにする。
  # URL /users/sign_in ...

  devise_scope :user do
    # ゲストログイン
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in',as: 'guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {

    # ユーザー新規登録画面
    registrations: "public/registrations",
    # ログイン画面
    sessions: 'public/sessions'

  }

  scope module: :public do
    # トップページ　初期表示
    root to: 'homes#top'
    # アバウトページ
    get 'about' => 'homes#about', as: 'about'

    # マイページ
    get 'users/my_page' => 'users#my_page', as: 'my_page'
    # プロフィール編集画面
    get 'users/information/edit'=> 'users#edit', as: 'edit_information_users'
    # プロフィール更新
    patch 'users/information' => 'users#update', as: 'update_information_users'
    # 退会確認画面
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 退会処理
    patch 'users/goodbye' => 'users#goodbye', as: 'goodbye'
    # ユーザー詳細画面
    resources :users, only: [:show] do

      # ユーザーの投稿内容一覧
      get 'posts'
      # ユーザーのコメント一覧
      get 'comments'
       # ユーザーのいいね一覧
      get 'favorites'
    end

    # 投稿内容一覧（ユーザー投稿全て）⇒　削除
    # get 'posts/user_index' => 'posts#user_index', as: 'user_index'
    resources :posts do

      # コメント機能
      resources :comments, only: [:create,:edit,:update,:destroy]
      # いいね機能
      resources :favorites, only: [:create, :destroy]
    end

    # ねこずかん（種類一覧）系
    resources :types, only: [:index, :show]

  end

    # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

    # 管理者ログイン
    sessions: "admin/sessions"
  }

  # 管理者用
  get 'admin' => 'admin/homes#top', as: 'admin_home_top'

  namespace :admin do

    # ユーザー一覧系
    resources :users, only: [:index, :show, :edit, :update]
    # 投稿内容一覧系
    resources :posts, only: [:show, :destroy]
    # コメント一覧系
    resources :comments, only: [:index, :destroy]
    # ねこずかん（種類一覧）系
    resources :types

  end

end

app/models/user.rb
class User < ApplicationRecord

  # device 使用

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 1 : N　の関連付け（アソシエーション: association）
  # posts と users の 1 : N のアソシエーション実装
  has_many :posts, dependent: :destroy
  # favorites と users の 1 : N のアソシエーション実装
  has_many :favorites, dependent: :destroy
  # comments と users の 1 : N のアソシエーション実装
  has_many :comments, dependent: :destroy

  # バリデーション(入力必須のバリデーションをまとめる。)
  with_options presence: true do

    # ユーザー名
    validates :name
    # 性別
    validates :sex
    # メールアドレス
    validates :email
    # 自己紹介文
    validates :self_introduction

  end

  # ActiveStorage(imageカラム)を追加して、画像を投稿出来るようにする。
  has_one_attached :image

  # 性別のenum（0：その他、1：男、2：女）
  enum sex: { another: 0, male: 1, famale: 2 }

  # ゲストログイン時のデータを作成
  def self.guest

    # ユーザーモデルで、ゲストログイン用のメールアドレスが、1件あるか確認する。
    find_or_create_by!(email: 'guest@nekoha.com') do |user|

      #　パスワードをランダム生成
      user.password = SecureRandom.urlsafe_base64
      #　確認用パスワード
      user.password_confirmation = user.password
      #　ユーザーネーム
      user.name = 'ゲスト'
      #　性別
      user.sex = 0
      #　自己紹介文
      user.self_introduction = "ゲストログイン用です。"
      # 退会ステータス
      user.is_deleted = false

    end

  end

  # プロフィール画像を取得する。（第1引数：サイズ）
  def get_profile_image(size)

    # 画像を取得出来るか
    upload_default_image unless image.attached?
    # 画像サイズの変更(px)
    image.variant(resize: size).processed

  end

  # プロフィール画像が存在しない場合、イメージなしの画像を取得する。
  def upload_default_image

    # 画像なしの場合のjpeg画像を取得する。
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')

  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  # コントローラーに設定して、ログイン済管理者のみにアクセスを許可する
  before_action :authenticate_admin!

  # ユーザー一覧
  def index

    # ユーザーモデルから1ページ分（データ30件）取得（降順）
    @users = User.page(params[:page]).per(30).order(id: "DESC")

  end

  # ユーザー詳細
  def show

    # 1件ユーザー情報取得
    @user = user_find_params_id

  end

  # ユーザー編集画面
  def edit

    # 1件ユーザー情報取得
    @user = user_find_params_id

  end

  # ユーザー情報更新
  def update

    # 1件ユーザー情報取得
    @user = user_find_params_id

    # 更新時チェック
    if @user.update(user_params)

      # 成功時処理
      # フラッシュメッセージ
      notice("対象のユーザー情報を更新しました。")
      # 処理後遷移先
      redirect_to admin_user_path(@user.id)

    else

      # 失敗時処理
      # 処理後遷移先
      render :edit

    end

  end

  private

  # ストロングパラメータ
  def user_params

    # userタイプのモデル
    params.require(:user).permit(:name,:sex,:email,:self_introduction,:is_deleted)

  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class = "row">
  <div class = "offset-1 col-7">
  <h4>ユーザー編集</h4>
  <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
  <!-- エラーメッセージ -->
  <%= render 'layouts/error_messages', model: f.object %>
    <div class = "field my-2 offset-1">
      <table class = "table table-borderless" >
        <tbody>
          <!-- ユーザーID -->
          <tr>
            <th>ユーザーID</th>
            <td><%= @user.id %></td>
          </tr>
          <!-- ユーザー名 -->
          <tr>
            <th>ユーザー名</th>
            <td><%= f.text_field :name, :placeholder => "ネコハ太郎", autofocus: true, maxlength: "20" %></td>
          </tr>
          <!-- 性別 -->
          <tr>
            <th>性　　別</th>
            <td><%= f.select :sex, User.sexes_i18n.invert %></td>
          </tr>
          <!-- メールアドレス -->
          <tr>
            <th>メールアドレス</th>
            <td><%= f.email_field :email, :placeholder => "sample@example.com" %></td>
          </tr>
          <!-- 自己紹介文 -->
          <tr>
            <th>自己紹介文</th>
            <td><%= f.text_area :self_introduction, :placeholder => "よろしくお願いいたします。" , size: "50x10" %></td>
          </tr>
          <!-- ステータス　ラジオボタンで変更できる。-->
          <tr>
            <th>ステータス</th>
            <td colspan="2">
              <!-- 有効 -->
              <div>
                <%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, '有効' %>
              </div>
              <!-- 退会 -->
              <div>
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, '退会' %>
              </div>
            </td>
          </tr>
          <tr>
            <th></th>
            <td>
              <div class="d-flex justify-content-lg-between">
                <!-- 更新ボタン -->
                <%= f.submit '更新', class:"btn btn-success btn-block" %>
              </div>
            </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>

app/views/admin/users/index.html.erb
<div class = "d-flex justify-content-between">
  <h4 class = "field m-3">ユーザー一覧</h4>
</div>
<div>
  <!-- テーブルヘッダー部分 -->
  <table class = "table" >
    <thead class = "table-warning">
      <tr>
        <th>ユーザーID</th>
        <th>ユーザー名</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <!-- ユーザーモデルから1ページ分（データ30件） -->
      <% @users.each do |f| %>
      <tr>
        <!-- ユーザーID -->
        <td><%= f.id %></td>
        <td>
          <!-- ユーザー詳細画面へのリンク -->
          <%= link_to admin_user_path(f.id) do %>
            <!-- ユーザー名 -->
            <%= f.name %>
          <% end %>
        </td>
        <!-- ユーザーのステータス -->
        <% if f.is_deleted %>
          <!-- 退会 -->
          <td class = "text-danger"><p class="font-weight-bold">退会</p></td>
        <% else %>
          <!-- 有効（ログイン可能） -->
          <td class = "text-success"><p class="font-weight-bold">有効</p></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- ページリンク -->
<div class = "d-flex justify-content-center">
  <%= paginate @users %>
</div>

app/views/admin/users/show.html.erb
<div class = "row">
  <div class = "offset-1">
    <h4>ユーザー詳細</h4>
    <!-- ユーザー画像 -->
    <div class = "items_image offset-1">
      <%= image_tag @user.get_profile_image(200) %>
    </div>
  </div>

  <div class = "field my-2 offset-1">
    <table class = "table table-borderless" >
      <tbody>
        <!-- ユーザーID -->
        <tr>
          <th>ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <!-- ユーザー名 -->
        <tr>
          <th>ユーザー名</th>
          <td><%= @user.name %></td>
        </tr>
        <!-- 性別（enum） -->
        <tr>
          <th>性　　別</th>
          <td><%= User.sexes_i18n[@user.sex] %></td>
        </tr>
        <!-- メールアドレス -->
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <!-- 自己紹介文 -->
        <tr>
          <th>自己紹介文</th>
          <td><%= @user.self_introduction %></td>
        </tr>
       <!-- ユーザーステータス -->
        <tr>
          <th>ユーザー</th>
          <% if @user.is_deleted %>
            <!-- 退会 -->
            <td class = "text-danger"><p class="font-weight-bold">退会</p></td>
          <% else %>
            <!-- 有効 -->
            <td class = "text-success"><p class="font-weight-bold">有効</p></td>
          <% end %>
        </tr>
      </tbody>
    </table>
     <div class="d-flex justify-content-lg-between">
      <!-- 編集ボタン -->
      <%= link_to "編集", edit_admin_user_path(@user.id), class:"btn btn-success btn-block" %>
    </div>
  </div>
</div>