config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # moduleで、URLを変更せず、ファイル構成だけ指定のパスにする。
  # URL /users/sign_in ...

  devise_scope :user do
    # ゲストログイン
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in',as: 'guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {

    # ユーザー新規登録画面
    registrations: "public/registrations",
    # ログイン画面
    sessions: 'public/sessions'

  }

  scope module: :public do
    # トップページ　初期表示
    root to: 'homes#top'
    # アバウトページ
    get 'about' => 'homes#about', as: 'about'

    # マイページ
    get 'users/my_page' => 'users#my_page', as: 'my_page'
    # プロフィール編集画面
    get 'users/information/edit'=> 'users#edit', as: 'edit_information_users'
    # プロフィール更新
    patch 'users/information' => 'users#update', as: 'update_information_users'
    # 退会確認画面
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 退会処理
    patch 'users/goodbye' => 'users#goodbye', as: 'goodbye'
    # ユーザー詳細画面
    resources :users, only: [:show] do

      # ユーザーの投稿内容一覧
      get 'posts'
      # ユーザーのコメント一覧
      get 'comments'
       # ユーザーのいいね一覧
      get 'favorites'
    end

    # 投稿内容一覧（ユーザー投稿全て）⇒　削除
    # get 'posts/user_index' => 'posts#user_index', as: 'user_index'
    resources :posts do

      # コメント機能
      resources :comments, only: [:create,:edit,:update,:destroy]
      # いいね機能
      resources :favorites, only: [:create, :destroy]
    end

    # ねこずかん（種類一覧）系
    resources :types, only: [:index, :show]

  end

    # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

    # 管理者ログイン
    sessions: "admin/sessions"
  }

  # 管理者用
  get 'admin' => 'admin/homes#top', as: 'admin_home_top'

  namespace :admin do

    # ユーザー一覧系
    resources :users, only: [:index, :show, :edit, :update]
    # 投稿内容一覧系
    resources :posts, only: [:show, :destroy]
    # コメント一覧系
    resources :comments, only: [:index, :destroy]
    # ねこずかん（種類一覧）系
    resources :types

  end

end

app/views/layouts/_admin_post_tag_list.html.erb
<!-- 投稿時に、登録したタグの分だけ、ループする。 -->
<% tag_list.each do |tag|%>
  <div class="btn btn-primary">
    <%= tag %>
  </div>
<% end %>

app/views/layouts/_admin_type_tag_list.html.erb
<!-- 投稿時に、登録したタグの分だけ、ループする。 -->
<% tag_list.each do |tag|%>
  <div class="btn btn-primary">
    <%= tag %>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<!-- モデルのバリデーション分の数だけエラーを出力する。 -->
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- フッター部分 -->
<footer class="bg-secondary text-white pt-5 pb-4">
  <div class="container">
    <div class="small text-center text-white" style="margin: 50px 0;">
       @2023 nekoha
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- ヘッダー部分 -->
   <header class ="header bg-secondary">
      <nav class="navbar navbar-expand-lg border border-bottom-dark">
        <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <!-- ロゴ（トップページへ遷移する。） -->
            <%= link_to root_path do %>
              <%= image_tag 'logo.png' ,:width => '120', :height => '120' %>
            <% end %>
          </nav>
          <nav class="nav navbar-nav navbar-left">
            <!-- ログイン済みかつ退会していないか -->
            <% if user_signed_in? && !current_user.is_deleted %>
              <li>
                <div class="nav navbar-right text-light">
                  <!-- ユーザー名 -->
                  ユーザー名：<%= current_user.name %>
                </div>
              </li>
            <% end %>
          </nav>
          <nav>
             <ul class="nav navbar-right">
               <!-- ログイン済みかつ退会していないか -->
              <% if user_signed_in? && !current_user.is_deleted %>
                <!-- 投稿内容一覧 -->
                <li>
                  <%= link_to posts_path, class:"nav-link text-light" do %>
                    <i class="fas fa-search"></i>
                  <% end %>
                </li>
                <!-- アバウトページ -->
                <li>
                  <%= link_to about_path, class:"nav-link text-light bg-dark" do %>
                    About
                  <% end %>
                </li>
                <!-- マイページ -->
                <li>
                  <%= link_to my_page_path, class:"nav-link text-light bg-dark" do %>
                    マイページ
                  <% end %>
                </li>
                <!-- ログアウト -->
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light bg-dark" do %>
                    ログアウト
                  <% end %>
                </li>
                <!-- ねこずかん -->
                <li>
                  <%= link_to types_path, class:"nav-link text-light bg-dark" do %>
                    ねこずかん
                  <% end %>
                </li>
              <!-- 管理者側 -->
              <% elsif admin_signed_in? %>
                <!-- ユーザー一覧 -->
                <li>
                  <%= link_to admin_users_path, class:"nav-link text-light bg-dark" do %>
                    ユーザー一覧
                  <% end %>
                </li>
                <!-- コメント一覧 -->
                <li>
                  <%= link_to admin_comments_path, class:"nav-link text-light bg-dark" do %>
                    コメント一覧
                  <% end %>
                </li>
                <!-- 投稿内容一覧 -->
                <li>
                  <%= link_to admin_home_top_path, class:"nav-link text-light bg-dark" do %>
                    投稿内容一覧
                  <% end %>
                </li>
                <!-- ログアウト -->
                <li>
                <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-light bg-dark" do %>
                  ログアウト
                <% end %>
                <!-- ねこずかん -->
                <li>
                  <%= link_to admin_types_path, class:"nav-link text-light bg-dark" do %>
                    ねこずかん
                  <% end %>
                </li>
              </li>
              <!-- ログインしていない場合 -->
              <% else %>
                <!-- 投稿内容一覧 -->
                <li>
                  <%= link_to posts_path, class:"nav-link text-light" do %>
                    <i class="fas fa-search"></i>
                  <% end %>
                </li>
                <!-- アバウトページ -->
                <li>
                  <%= link_to about_path, class:"nav-link text-light bg-dark" do %>
                    About
                  <% end %>
                </li>
                <!-- 新規登録画面 -->
                <li>
                  <%= link_to new_user_registration_path, class:"nav-link text-light bg-dark" do %>
                    新規登録
                  <% end %>
                </li>
                <!-- ログイン画像-->
                <li>
                  <%= link_to new_user_session_path, class:"nav-link text-light bg-dark" do %>
                    ログイン
                  <% end %>
                </li>
                <!-- ねこずかん-->
                <li>
                  <%= link_to types_path, class:"nav-link text-light bg-dark" do %>
                    ねこずかん
                  <% end %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </nav>
    </header>

app/views/layouts/_post_tag_list.html.erb
<!-- 投稿時に、登録したタグの分だけ、ループする。 -->
<% tag_list.each do |tag|%>
  <div class="d-grid gap-2 btn btn-primary">
    <!-- タグ検索を行うためにリンク化。postモデルを検索 -->
    <%= link_to tag, posts_path(tag_name: tag), class: "text-white"  %>
  </div>
<% end %>

app/views/layouts/_tag_list.html.erb
<% tag_list.each do |tag|%>
  <div class="btn btn-primary">
    <%= tag %>
  </div>
<% end %>

app/views/layouts/_type_tag_list.html.erb
<!-- 投稿時に、登録したタグの分だけ、ループする。 -->
<% tag_list.each do |tag|%>
  <div class="btn btn-primary">
    <!-- タグ検索を行うためにリンク化。typeモデルを検索 -->
    <%= link_to tag, types_path(tag_name: tag), class: "text-white"  %>
  </div>
<% end %>

app/views/layouts/_users_sidebar.html.erb
<!-- ログイン時に出力するサイドバー -->
<div class = "genres_sidebar" >
  <table>
    <tbody>
      <!-- 投稿する -->
      <tr>
        <td>
          <%= link_to "投稿する", new_post_path %>
        </td>
      </tr>
      <!-- 投稿内容一覧（ユーザー） -->
      <tr>
        <td>
          <%= link_to "投稿内容一覧", user_posts_path(current_user.id) %>
        </td>
      </tr>
      <!-- いいね一覧 -->
      <tr>
        <td>
          <%= link_to "いいね一覧", user_favorites_path(current_user.id) %>
        </td>
      </tr>
       <!-- コメント一覧 -->
      <tr>
        <td>
          <%= link_to "コメント一覧", user_comments_path(current_user.id) %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nekoha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <%= render "layouts/header" %>
    </div>
    <main>
      <div class="container" style="margin-top: 10px;">
        <div class = "d-flex justify-content-around">
          <p class ="notice text-success"><%= flash[:notice] %></p>
        </div>
        <%= yield %>
      </div>
    </main>
    <div id="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>